package com.cos.opgg.api.apimodel.attr.match;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Stats {

    private long participantId;
    private boolean win;
    private long item0;
    private long item1;
    private long item2;
    private long item3;
    private long item4;
    private long item5;
    private long item6;
    private long kills;
    private long deaths;
    private long assists;
    private long largestKillingSpree;
    private long largestMultiKill;
    private long killingSprees;
    private long longestTimeSpentLiving;
    private long doubleKills;
    private long tripleKills;
    private long quadraKills;
    private long pentaKills;
    private long unrealKills;
    private long totalDamageDealt;
    private long magicDamageDealt;
    private long physicalDamageDealt;
    private long trueDamageDealt;
    private long largestCriticalStrike;
    private long totalDamageDealtToChampions;
    private long magicDamageDealtToChampions;
    private long physicalDamageDealtToChampions;
    private long trueDamageDealtToChampions;
    private long totalHeal;
    private long totalUnitsHealed;
    private long damageSelfMitigated;
    private long damageDealtToObjectives;
    private long damageDealtToTurrets;
    private long visionScore;
    private long timeCCingOthers;
    private long totalDamageTaken;
    private long magicalDamageTaken;
    private long physicalDamageTaken;
    private long trueDamageTaken;
    private long goldEarned;
    private long goldSpent;
    private long turretKills;
    private long inhibitorKills;
    private long totalMinionsKilled;
    private long neutralMinionsKilled;
    private long neutralMinionsKilledTeamJungle;
    private long neutralMinionsKilledEnemyJungle;
    private long totalTimeCrowdControlDealt;
    private long champLevel;
    private long visionWardsBoughtInGame;
    private long sightWardsBoughtInGame;
    private long wardsPlaced;
    private long wardsKilled;
    private boolean firstBloodKill;
    private boolean firstBloodAssist;
    private boolean firstTowerKill;
    private boolean firstTowerAssist;
    private boolean firstInhibitorKill;
    private boolean firstInhibitorAssist;
    private long combatPlayerScore;
    private long objectivePlayerScore;
    private long totalPlayerScore;
    private long totalScoreRank;
    private long playerScore0;
    private long playerScore1;
    private long playerScore2;
    private long playerScore3;
    private long playerScore4;
    private long playerScore5;
    private long playerScore6;
    private long playerScore7;
    private long playerScore8;
    private long playerScore9;
    private long perk0;
    private long perk0Var1;
    private long perk0Var2;
    private long perk0Var3;
    private long perk1;
    private long perk1Var1;
    private long perk1Var2;
    private long perk1Var3;
    private long perk2;
    private long perk2Var1;
    private long perk2Var2;
    private long perk2Var3;
    private long perk3;
    private long perk3Var1;
    private long perk3Var2;
    private long perk3Var3;
    private long perk4;
    private long perk4Var1;
    private long perk4Var2;
    private long perk4Var3;
    private long perk5;
    private long perk5Var1;
    private long perk5Var2;
    private long perk5Var3;
    private long perkPrimaryStyle;
    private long perkSubStyle;
    private long statPerk0;
    private long statPerk1;
    private long statPerk2;

}